version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:5.0
    container_name: devops-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: devops-backend
    volumes:
      - mongo_data:/data/db
    networks:
      - devops-network

  # Node.js backend service
  app:
    build: .
    container_name: devops-backend
    ports:
      - "8000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/devops-backend
      PORT: 5000
    depends_on:
      - mongo
    networks:
      - devops-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  devops-network:
    driver: bridge
